import type { Metadata } from "next";
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Company Profile",
  description: "Generated by create next app",
};
const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700"],
  variable: "--font-oswald",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${roboto.variable}`}>
        <div
          className={
            "w-screen h-screen bg-gradient-to-b from-blue-100 to-green-100"
          }
        >
          {" "}
          <div className="h-24">
            <Navbar />
          </div>
          <div className="h-[clac(100vh-6rem)]">{children}</div>
          <div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
